/**
 * Build Configuration (Auto-generated)
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * Generated by scripts/generate-build-config.js
 *
 * Build type: production-free
 * Premium features: DISABLED
 */

/**
 * Build-time constant controlling premium feature availability
 * - Free builds: false (premium code removed by TypeScript + minifier)
 * - Premium builds: true (premium code included)
 * - This constant is replaced at build time based on BUILD_PREMIUM env variable
 */
export const PREMIUM_FEATURES_AVAILABLE = false;

/**
 * Build type identifier
 */
export const BUILD_TYPE = 'production-free' as const;

/**
 * Build timestamp
 */
export const BUILD_TIMESTAMP = 1769952712936;
